[rf]
freq_offset = 0
tx_gain = 75
rx_gain = 40
srate = 11.52e6
nof_antennas = 1
device_name = zmq
# mirror of the gNB ZMQ ports: UE tx -> gNB rx (2001), UE rx <- gNB tx (2000)
device_args = tx_port=tcp://10.53.1.20:2001,rx_port=tcp://10.53.1.10:2000,base_srate=11.52e6

[rat.eutra]
dl_earfcn = 2850
nof_carriers = 0

[rat.nr]
bands = 3
nof_carriers = 1
max_nof_prb = 52
nof_prb = 52

[pcap]
enable = none

[log]
all_level = info
filename = /tmp/ue.log
file_max_size = -1

[usim]
mode = soft
algo = milenage
opc  = 63BFA50EE6523365FF14C1F45F88737D
k    = 00112233445566778899aabbccddeeff
imsi = 001010000000001
imei = 353490069873319

[rrc]
release = 15
ue_category = 4

[nas]
apn = internet
apn_protocol = ipv4

[gw]
netns =

[gui]
enable = false
