name = "CCD"
version = "0.0.1"
keywords = ["math"]
defaultTargets = ["CCD"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = false # downstream project (not destined for Mathlib)
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.31.0"

[[lean_lib]]
name = "CCD"
